--- application.py	2020-08-05 13:27:27.798088979 +0200
+++ application.py.new	2020-08-05 12:16:49.406539618 +0200
@@ -86,6 +86,13 @@
     else:
         LOG.warning(six.text_type(error))

<% if @is_production -%> 
+    # Keystone-patch-0002
+    if error.code >= 400 and flask.request.referrer:
+        if 'idp.infn.it' in flask.request.referrer or 'cloud-areapd.pd.infn.it' in flask.request.referrer:
+            return flask.redirect("https://cloud-areapd.pd.infn.it/dashboard/auth/auth_error/")
+        if 'shibidp.cca.unipd.it' in flask.request.referrer or 'cloudveneto.ict.unipd.it' in flask.request.referrer:
+            return flask.redirect("https://cloudveneto.ict.unipd.it/dashboard/auth/auth_error/")
+
<% else -%>
+    # Keystone-patch-0002
+    if error.code >= 400 and flask.request.referrer:
+        if 'idp.infn.it' in flask.request.referrer or 'cloud-areapd-test.pd.infn.it' in flask.request.referrer:
+            return flask.redirect("https://cloud-areapd-test.pd.infn.it/dashboard/auth/auth_error/")
+        if 'shibidpdev.cca.unipd.it' in flask.request.referrer or 'cloudveneto-test.ict.unipd.it' in flask.request.referrer:
+            return flask.redirect("https://cloudveneto-test.ict.unipd.it/dashboard/auth/auth_error/")
+
<% end -%>
     # Render the exception to something user "friendly"
     error_message = error.args[0]
     message = oslo_i18n.translate(error_message, _best_match_language())
